In [1]:
import numpy as np
import scipy.stats as stats

In [2]:
# shift + enter to initiate this array
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [3]:
#1
# use the function for any number in the array of numbers, count the number of numbers that when divided by 2,
# have a remainder of 1, which means it is odd
# .shape will count the numbers it returns
a[a % 2 == 1].shape

(4,)

In [4]:
#2
# use the function for any number in the array of numbers, count the number of numbers that when divided by 2,
# have a remainder of zero, which means it is even
a[a % 2 == 0].shape

(8,)

In [5]:
#3
# first we break the function down to find evens
# then we use the & symbol to join the arguments together in numpy
# then join on the argument that filters all the numbers in the array greater than 0 because 0 is a non-even number,
# we don't include zer0
# lastly, we finish with .shape to count the amount of numbers it returns true, meaning it met the criteria
a[(a % 2 == 0) & (a > 0)].shape

(3,)

In [6]:
#4
# I first created an argument that would add 3 to all the values in the array
# after that I added on the argument to return all the values greater than zero
#lastly, I added .shape for the count and the a[] to return the numbers rather than the boolean values
a[(a + 3) & (a > 0)].shape

(12,)

In [7]:
#5-1
#first I created the argument to square all the values in the array
# then i added the mean function to calculate the mean
(a ** 2).mean()

74.0

In [8]:
#5-2
#first I created the argument to square all the values in the array
# then i added the standard deviation function to calculate the standard deviation
(a ** 2).std()

144.0243035046516

In [9]:
#6
# I subtracted the mean of all the values in the array from each value in the array to center it
a - a.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [10]:
#7
# I decided to import scipy.stats because it has a lot of stats functions for python
# then I just used the zscore function of the array
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [11]:
## 8
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

In [12]:
sum_of_a = sum(a)
print(sum_of_a)

55


In [13]:
min_of_a = min(a)
print(min(a))

1


In [14]:
max_of_a = max(a)
print(max(a))

10


In [15]:
mean_of_a = sum(a) / len(a)
print(mean_of_a)

5.5


In [67]:
product_of_a = 1
for n in a:
    product_of_a *= n
print(product_of_a)

3628800


In [17]:
squares_of_a = [n ** 2 for n in a]
print(squares_of_a)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [18]:
def odds_in_a(a):
    for n in a:
        if n % 2 == 0:
            return n

In [19]:
def evens_in_a(a):
    for n in a:
        if n % 2 == 1:
            return n

In [20]:
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

# Exercise 9 - print out the shape of the array b.

# Exercise 10 - transpose the array b.

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)



In [21]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [22]:
#1
b.sum()

33

In [23]:
#2
b.min()

3

In [24]:
#3
b.max()

8

In [25]:
#4
b.mean()

5.5

In [26]:
#5
b.prod()

20160

In [27]:
#6
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [28]:
#7
b[b % 2 == 1]

array([3, 5, 7])

In [29]:
#8
b[b % 2 == 0]

array([4, 6, 8])

In [30]:
#9
print(b.shape)

(2, 3)


In [32]:
#10
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [39]:
#11
np.reshape(b, (1, 6))

array([[3, 4, 5, 6, 7, 8]])

In [40]:
#12
np.reshape(b, (6, 1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [44]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
    
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

# Exercise 2 - Determine the standard deviation of c.

# Exercise 3 - Determine the variance of c.

# Exercise 4 - Print out the shape of the array c

# Exercise 5 - Transpose c and print out transposed result.

# Exercise 6 - Get the dot product of the array c with c. 

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [ ]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [89]:
#1
c.min()

1

In [90]:
c.max()

9

In [91]:
c.sum()

45

In [92]:
c.prod()

362880

In [49]:
#2
c.std()

2.581988897471611

In [50]:
#3
c.var()

6.666666666666667

In [52]:
#4
c.shape

(3, 3)

In [53]:
#5
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [64]:
#6
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [69]:
#7
(np.transpose([c * c])).sum()

285

In [73]:
#8
np.transpose(c.prod() * c.prod())

131681894400

In [ ]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d

# Exercise 2 - Find the cosine of all the numbers in d

# Exercise 3 - Find the tangent of all the numbers in d

# Exercise 4 - Find all the negative numbers in d

# Exercise 5 - Find all the positive numbers in d

# Exercise 6 - Return an array of only the unique numbers in d.

# Exercise 7 - Determine how many unique numbers there are in d.

# Exercise 8 - Print out the shape of d.

# Exercise 9 - Transpose and then print out the shape of d.

# Exercise 10 - Reshape d into an array of 9 x 2

In [74]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [78]:
#1
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [80]:
#2
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [81]:
#3
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [84]:
#4
d[(d < 0)].shape

(4,)

In [86]:
#5
d[(d > 0)].shape

(12,)

In [98]:
#6
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [100]:
#7
np.unique(d).shape

(11,)

In [94]:
#8
d.shape

(3, 6)

In [96]:
#9
np.transpose(d).shape

(6, 3)

In [97]:
#10
np.reshape(d, (9, 2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])